'use client';
import {useState} from "react";
import Head from "next/head";

import styles from "@/styles/Home.module.css";



import Categorias from "@/components/Categorias";
import CampoDeBusca from "@/components/CampoDeBusca";


export default function Home(props) {


  
  
 
  

 
  return (
    <>



      <Head>
        <title>Cardapio Restaurante</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


              <div className={styles.container}>

                      <h1>RESTAURANT</h1>
                      <p>De pratos clássicos a criações surpreendentes,  nosso cardápio é um requinte de sabores  refinados
                      </p>

              </div>
  

              <Categorias/>
         
        
            
              
            

          




     


    </>
  );
}
